import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import Navbar from "@/components/shared/Header/Navbar";

const inter = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{scrollBehavior: "smooth"}}>
      <body className={`${inter.className} pattern-bg`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
